### ISSUE TITLE
Expected output file *._000002.hist-output.root does not exist 

### ISSUE THREAD

**Issue by joliver92** [rsmith54/RJigsawTools#110]
Hi guys, 

I am having an issue with jobs running on the grid. The issue seems to be from running the mc15c_SM_SUSY2 samples provided in the RJigsaw/data folder. I'm not exactly sure where the issue is but perhaps you can point me in the correct direction. 

I am running the run_lvlv.py script, and interested in putting the Hemisphere variables from _tls.py into the analysis. To do this i changed the calculator in run_lvlv.py to  .tlsCalcultor(); (with the appropriate syntax). 

When i submitted the job with this script to the grid half the datasets run without issue, the otherhalf return with an error, namely 

Expected output file panda.um.user.jaoliver.8450305._000002.hist-output.root does not exist

now, i thought this was because i changed the calcultor to .tlscalcultor  so i tried it with the lvlv calcultor for the RJigsaw variables. I get the same hist-output.root error.

I have looked for the datasets using rucio and all the datasets i checked were available. 

is this a known issue?

thanks for the help you've provided,

Jason

**Comment by rsmith54** [comment]
Hi @JOliver-GH ,

You have a seg fault, since you are running a 2.3.X analysis release on a 20.7 sample.  Please use the setup script in the util folder; this will always setup the proper analysis release (currently 2.4.7).  In a fresh setup, you can just write :

`source FactoryTools/util/setup.sh`
`rc find_packages`
`rc compile`

Also try and link to your jobs the athena_stdout.txt for your jobs to help with debugging (see below).

Cheers,
Russell

PS : You should really remove all of your debug output (the MET_SR : X) before submitting to the grid; jobs will be much much slower if you are printing in every single event.

http://aipanda058.cern.ch/media/filebrowser/058d19c6-a5ed-43c1-8695-c66181af8e39/panda/tarball_PandaJob_2863627506_ANALY_TOKYO/athena_stdout.txt
