### ISSUE TITLE
Add calculator for 2L strong decay tree

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#33]
We need a calculator for the 2L strong decay tree.

**Comment by lawrenceleejr** [comment]
@dylanpeukert See #47.

You'll have to change the type of some of your objects from IParticles to Particles. This change was made mainly for the two lepton case so that we can carry around information about the leptons into the calculator.

**Comment by lawrenceleejr** [comment]
@dylanpeukert how's this coming along? Once you have a version that works with the current master (do a git pull and make sure you're compatible with the recent changes yesterday), push to your dev branch and when you have something working, we can submit a pull request for your additions to get into master.

**Comment by dylanpeukert** [comment]
@lawrenceleejr I've added my code to dev-Dylan. It should be compatible with the code on master, however I haven't yet got either the merged code or the master to work.
This is likely due to not having the right setup of the prerequisite code.
When run with my old setup the code compiled but only the lvlv analysis failed giving the following error:
GoodRunsListSelectionTool ERROR   /build2/atnight/localbuilds/nightlies/AnalysisSUSY-2.3.X/AnalysisSUSY/rel_nightly/GoodRunsLists/Root/GoodRunsListSelectionTool.cxx:129 (virtual StatusCode GoodRunsListSe\
lectionTool::initialize()): Cannot open file : /afs/cern.ch/work/d/dpeukert/SUSY2L/RootCoreBin/data/xAODAnaHelpers/data15_13TeV.periodAllYear_HEAD_DQDefects-00-01-02_PHYS_StandardGRL_Atlas_Ready.xml
BasicEventSelection::i... ERROR   /afs/cern.ch/work/d/dpeukert/SUSY2L/xAODAnaHelpers/Root/BasicEventSelection.cxx:577 Failed to execute: m_grl->initialize()

This is likely due to a different version of susy tools used in the master, however with the new version 
QuickAnna failed to compile. Any advice would be appreciated. Dylan

**Comment by lawrenceleejr** [comment]
Hi Dylan,

Please try to delete the packages xAODAnaHelpers, QuickAna, and CommonTools. Then from a new session try setting up RJigsawTools again following the instructions in the current README. The versions for these packages were changing under our feet so the current instructions say to checkout particular releases, and that should fix the issue. 

https://github.com/rsmith54/RJigsawTools/blob/master/README.md

In particular...

```
git clone https://github.com/lawrenceleejr/Ext_RestFrames.git
rc checkout_pkg atlasoff/PhysicsAnalysis/TopPhys/QuickAna/tags/QuickAna-00-00-94 QuickAna
rc checkout_pkg svn+ssh://svn.cern.ch/reps/atlasinst/Institutes/LBNL/AnalysisToolsRunII/CommonTools/tags/CommonTools-00-00-17 CommonTools
git clone https://github.com/UCATLAS/xAODAnaHelpers.git; cd xAODAnaHelpers; git checkout 00-03-27; cd ..;
```

-L

**Comment by rsmith54** [comment]
I was able to use update this code into the master, so I'm going to close this issue since the upgrades are mostly what we are trying to do in #52
